--- 
author: ~
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Jifty-Plugin-ModelMap
no_index: 
  directory: 
    - inc
    - t
requires: 
  GraphViz: 0
  HTML::Entities: 0
  Jifty: 0
  Memoize: 0
version: 0.02
